### PR TITLE
Added XMLConfigurator to initialize LoggingConfiguration using XML file

### PR DESCRIPTION
**Pull request by thomasgalliker**
Originally, I wanted to rewrite log4net to support PCL and Xamarin. But as you may know log4net is thoroughly overfilled with preprocessor directives and .net CLR 2.0 data types.
MetroLog was exactly what I needed - but there was lack of support for xml configuration file based logger setup. Thus, I wrote an pretty dynamic XMLConfigurator for MetroLog. Could you have a look into it and let me know if this is something you might want to integrate into MetroLog-master?
I'm new to github, so, let me know if this is the way to bring in changes. Also, let me know if you want me to improve my contribution.

### CODE REVIEW

**Comment by thomasgalliker** [comment]
Huh, something went wrong here. Seems as I committed into this PR continuously. Are you interested in having XML configurability at all? I personally like it but if you have no Intention of ever integrating such a feature into the MetroLog origin, we can remove this PR.

**Comment by onovotny** [comment]
I'd be curious as to why XML config is preferable to code-based config in the context of mobile apps? In those scenarios you'd typically build a package and not be able to easily edit a config file on-the-fly anyway?

**Comment by thomasgalliker** [comment]
Yes, true. My question at this time was: How can I make sure that I have the same logging configuration on all target platforms? - Imagine you have a Xamarin Android, iOS and a WP8 app which share their common code in a PCL library. I didn't check your latest changes but at this time it was not impossible to configure a JsonTarget from within the PCL project.

I agree that XML configurations are not always a good choice - especially in mobile app (because here we usually don't want to change configuration values at runtime). Nevertheless, I don't see another solution right now.

**Comment by onovotny** [comment]
Check out the latest in the dev branch:
https://ci.appveyor.com/project/onovotny/metrolog/build/artifacts

I've switched it to a bait-and-switch PCL so you can now create many of the targets in the PCL. I still need to move the file targets in to the PCL but it should be possible as a façade.

**Comment by onovotny** [comment]
StreamingFileTarget should be creatable from a PCL now too

**Comment by thomasgalliker** [comment]
This is indeed the better approach. Let me know if I can help you with something! There are also other things in this PR but I may check all changes and file them as issues. (E.g. async sending of json messages to a web target does not work in case an unhandled exception happens. Also, I added crash recording history, so that - in case of an application crash I can see the last n log entries of all severities. This is a really really helpful feature for debugging production mobile apps).

**Comment by onovotny** [comment]
if you could please rebase your individual changes off of the dev branch as separate PR's, I'd be happy to take them.

At this point it's mostly a matter of testing things, especially creating the StreamingFileTarget from a PCL. The inheritance hierarchy in the façade is slightly different than the runtime but not in a way that should affect anything...but that needs to be confirmed.

**Comment by thomasgalliker** [comment]
Ok. I close this PR for now. I saw you contributed a lot into MetroLog :+1: . I start off with your latest dev and check the gap to get my apps running with the same comfort as I have now.

**Pull request closed without merging**
